spring.application.name=SpringDemoApp

# declaring my own secret key for JWT
app_secret_key=QbhI4P1Sxr9hadY0ATkQX+O0dNn6fg+pT0B5FB2TqFFpkHvN5bE8O8Tll02Y1/dXLH+V4jNFoGl2fFdDnzwnMA==

# defining the root context path
server.servlet.context-path=/api/v1

## setting config for data
#spring.datasource.url=jdbc:h2:mem:springbootdb
#spring.datasource.driver-class-name=org.h2.Driver

# attaching postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=12345678

spring.data.redis.url=redis://localhost:6379
spring.cache.type=redis

# show sql in console
spring.jpa.show-sql=true

# each time we run the app it will create tables so we need to set update setting not create
# not going to work with H2 DB cause it will delete all data everytime
spring.jpa.hibernate.ddl-auto=create

# deffering data inserting until table are created
spring.jpa.defer-datasource-initialization=true

# attaching auto insertion of data into the database at startup "data.sql"
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


# Enable by default H2 Console not necessary but can disable it later
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console




